org: chopar
app: aws-node-http-api-project
service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::import-product"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::import-product"

functions:
  importProductsFile:
    handler: index.importProductsFile
    events:
      - http:
          path: /import
          method: get
  importFileParser:
    handler: index.importFileParser
    events:
      - s3:
          bucket: import-product
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
