org: chopar
app: aws-node-http-api-project
service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
    allowCredentials: true
    authorizers:
      basicAuthorizer:
        type: request
        functionArn: arn:aws:lambda:us-east-1:653231333242:function:authorization-service-dev-api
        identitySource: $request.header.Authorization
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::import-product"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::import-product"
        - Effect: "Allow"
          Action:
            - "sqs:*"
          Resource:
            - "arn:aws:sqs:us-east-1:653231333242:catalogItemsQueue"
  environment:
    SQS_URL: "https://sqs.us-east-1.amazonaws.com/653231333242/catalogItemsQueue"

functions:
  importProductsFile:
    handler: index.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get
          authorizer:
            name: basicAuthorizer
  importFileParser:
    handler: index.importFileParser
    events:
      - s3:
          bucket: import-product
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
